services:
  frontend:
    build: ./public
    ports:
      - 5173:5173
    volumes:
      - ./public/src:/app/src
      - ./public/index.html:/app/index.html
      - ./public/vite.config.js:/app/vite.config.js
    networks:
      - frontend

  server:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/app/src
    networks:
      - frontend
      - backend
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hunter2
    ports:
      - 6033:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - backend

volumes:
  dbdata:
networks:
  backend:
  frontend:
