services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hunter2
    ports:
      - 6033:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1
    networks:
      - backend

volumes:
  dbdata:
networks:
  backend:
  frontend:
